"""require username

Revision ID: 872fd82de31d
Revises: 46a8982c019b
Create Date: 2023-10-16 11:41:54.067140

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '872fd82de31d'
down_revision = '46a8982c019b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('username',
               existing_type=sa.VARCHAR(),
               nullable=True)

    # ### end Alembic commands ###
