"""add role, created_at, and updated_at to cast_members

Revision ID: c132b7672f8c
Revises: ba349a19447e
Create Date: 2023-10-13 12:53:21.288514

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c132b7672f8c'
down_revision = 'ba349a19447e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.add_column(sa.Column('role', sa.String(), nullable=False))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('updated_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('cast_members', schema=None) as batch_op:
        batch_op.drop_column('updated_at')
        batch_op.drop_column('created_at')
        batch_op.drop_column('role')

    # ### end Alembic commands ###
