"""create cast_members belonging to productions

Revision ID: ae6fa028ecb2
Revises: 516173a7921b
Create Date: 2023-10-03 11:30:14.861942

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "ae6fa028ecb2"
down_revision = "516173a7921b"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "cast_members",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("production_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["production_id"],
            ["productions.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("cast_members")
    # ### end Alembic commands ###
